# Global Weather

- This is the analysis project to understand the weather of countries in 2024

In [18]:
import pandas as pd
import matplotlib.pyplot as plt

## Loading Data

In [2]:
df=pd.read_csv("GlobalWeatherRepository - GlobalWeatherRepository.csv")

## Inspecting Data

In [7]:
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 9:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 9:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55

In [8]:
df.tail()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 2:30,19.1,66.3,Partly Cloudy,...,16.35,18.15,2,2,6:18 AM,6:38 PM,2:36 AM,2:31 PM,Waning Crescent,31
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30,34.2,93.6,Sunny,...,61.15,64.45,3,8,5:41 AM,6:14 PM,2:02 AM,1:21 PM,Waning Crescent,35
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 9:30,19.3,66.7,Sunny,...,7.45,15.35,1,1,5:51 AM,6:17 PM,2:06 AM,1:45 PM,Waning Crescent,34
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 8:30,18.5,65.3,Sunny,...,5.45,6.15,1,1,6:14 AM,6:01 PM,1:26 AM,2:30 PM,Waning Crescent,33
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 8:30,17.4,63.3,Sunny,...,19.85,20.55,2,2,6:04 AM,5:49 PM,1:10 AM,2:22 PM,Waning Crescent,33

In [25]:
df.sample(5)

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
125610,Mauritius,Port Louis,-20.1619,57.4989,Indian/Mauritius,1771742700,2026-02-22 10:45:00,29.4,84.9,Overcast,...,6.65,8.950,1,1,6:05 AM,6:42 PM,10:29 AM,9:56 PM,Waxing Crescent,21
127385,Norway,Oslo,59.9167,10.7500,Europe/Oslo,1772519400,2026-03-03 07:30:00,5.0,41.0,Partly cloudy,...,11.05,15.950,1,1,7:10 AM,5:50 PM,6:05 PM,7:12 AM,Full Moon,100
107402,Brunei Darussalam,Bandar Seri Begawan,4.8833,114.9333,Asia/Brunei,1763622900,2025-11-20 15:15:00,29.4,84.9,Partly cloudy,...,15.15,15.450,1,2,6:09 AM,6:02 PM,5:53 AM,5:58 PM,New Moon,0
122789,Benin,Porto-Novo,6.4833,2.6167,Africa/Porto-Novo,1770533100,2026-02-08 07:45:00,28.3,82.9,Partly cloudy,...,15.95,39.950,2,2,7:07 AM,7:00 PM,No moonrise,11:42 AM,Waning Gibbous,65
59179,Pakistan,Islamabad,33.7000,73.1667,Asia/Karachi,1742204700,2025-03-17 14:45:00,25.0,77.0,Sunny,...,43.29,54.205,3,5,6:15 AM,6:16 PM,9:14 PM,7:30 AM,Waning Gibbous,94

## Checking Data Types

In [23]:
df.dtypes

country                                 object
location_name                           object
latitude                               float64
longitude                              float64
timezone                                object
last_updated_epoch                       int64
last_updated                    datetime64[ns]
temperature_celsius                    float64
temperature_fahrenheit                 float64
condition_text                          object
wind_mph                               float64
wind_kph                               float64
wind_degree                              int64
wind_direction                          object
pressure_mb                              int64
pressure_in                            float64
precip_mm                              float64
precip_in                              float64
humidity                                 int64
cloud                                    int64
feels_like_celsius                     float64
feels_like_fahrenheit                  float64
visibility_km                          float64
visibility_miles                         int64
uv_index                               float64
gust_mph                               float64
gust_kph                               float64
air_quality_Carbon_Monoxide            float64
air_quality_Ozone                      float64
air_quality_Nitrogen_dioxide           float64
air_quality_Sulphur_dioxide            float64
air_quality_PM2.5                      float64
air_quality_PM10                       float64
air_quality_us-epa-index                 int64
air_quality_gb-defra-index               int64
sunrise                                 object
sunset                                  object
moonrise                                object
moonset                                 object
moon_phase                              object
moon_illumination                        int64
dtype: object

In [22]:
df.columns

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination'],
      dtype='object')

In [24]:
df.shape

(135073, 41)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135073 entries, 0 to 135072
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       135073 non-null  object
 1   location_name                 135073 non-null  object
 2   latitude                      135073 non-null  float64
 3   longitude                     135073 non-null  float64
 4   timezone                      135073 non-null  object
 5   last_updated_epoch            135073 non-null  int64
 6   last_updated                  135073 non-null  datetime64[ns]
 7   temperature_celsius           135073 non-null  float64
 8   temperature_fahrenheit        135073 non-null  float64
 9   condition_text                135073 non-null  object
 10  wind_mph                      135073 non-null  float64
 11  wind_kph                      135073 non-null  float64
 12  wind_degree                   135073 non-null  int64
 13  wind_direction                135073 non-null  object
 14  pressure_mb                   135073 non-null  int64
 15  pressure_in                   135073 non-null  float64
 16  precip_mm                     135073 non-null  float64
 17  precip_in                     135073 non-null  float64
 18  humidity                      135073 non-null  int64
 19  cloud                         135073 non-null  int64
 20  feels_like_celsius            135073 non-null  float64
 21  feels_like_fahrenheit         135073 non-null  float64
 22  visibility_km                 135073 non-null  float64
 23  visibility_miles              135073 non-null  int64
 24  uv_index                      135073 non-null  float64
 25  gust_mph                      135073 non-null  float64
 26  gust_kph                      135073 non-null  float64
 27  air_quality_Carbon_Monoxide   135073 non-null  float64
 28  air_quality_Ozone             135073 non-null  float64
 29  air_quality_Nitrogen_dioxide  135073 non-null  float64
 30  air_quality_Sulphur_dioxide   135073 non-null  float64
 31  air_quality_PM2.5             135073 non-null  float64
 32  air_quality_PM10              135073 non-null  float64
 33  air_quality_us-epa-index      135073 non-null  int64
 34  air_quality_gb-defra-index    135073 non-null  int64
 35  sunrise                       135073 non-null  object
 36  sunset                        135073 non-null  object
 37  moonrise                      135073 non-null  object
 38  moonset                       135073 non-null  object
 39  moon_phase                    135073 non-null  object
 40  moon_illumination             135073 non-null  int64
dtypes: datetime64[ns](1), float64(21), int64(9), object(10)
memory usage: 42.3+ MB

## Dataset Overview

#### number of raws = 136633
#### number of columns = 41

## Selecting Columns

##### selecting single columns

In [28]:
df["country"]

0         Afghanistan
1             Albania
2             Algeria
3             Andorra
4              Angola
             ...
135068      Venezuela
135069        Vietnam
135070          Yemen
135071         Zambia
135072       Zimbabwe
Name: country, Length: 135073, dtype: object

In [29]:
df["sunset"]

0         6:50 PM
1         7:54 PM
2         7:50 PM
3         9:11 PM
4         5:55 PM
           ...
135068    6:38 PM
135069    6:14 PM
135070    6:17 PM
135071    6:01 PM
135072    5:49 PM
Name: sunset, Length: 135073, dtype: object

In [30]:
df[["longitude","latitude"]]

        longitude  latitude
0         69.1800   34.5200
1         19.8200   41.3300
2          3.0500   36.7600
3          1.5200   42.5000
4         13.2300   -8.8400
...           ...       ...
135068   -66.9167   10.5000
135069   105.8500   21.0333
135070    44.2067   15.3547
135071    28.2833  -15.4167
135072    31.0447  -17.8178

[135073 rows x 2 columns]

In [34]:
place=df[["country","location_name"]]

In [35]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,8.40,26.60,1,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,1.10,2.00,1,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,10.40,18.40,1,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,0.70,0.90,1,1,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,183.40,262.30,5,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,16.35,18.15,2,2,6:18 AM,6:38 PM,2:36 AM,2:31 PM,Waning Crescent,31
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,61.15,64.45,3,8,5:41 AM,6:14 PM,2:02 AM,1:21 PM,Waning Crescent,35
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,7.45,15.35,1,1,5:51 AM,6:17 PM,2:06 AM,1:45 PM,Waning Crescent,34
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,5.45,6.15,1,1,6:14 AM,6:01 PM,1:26 AM,2:30 PM,Waning Crescent,33
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,19.85,20.55,2,2,6:04 AM,5:49 PM,1:10 AM,2:22 PM,Waning Crescent,33

## Filtering The Data

# 1

In [37]:
df[df["temperature_celsius"]==26]

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,183.40,262.30,5,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55
5,Antigua and Barbuda,Saint John's,17.1200,-61.8500,America/Antigua,1715849100,2024-05-16 04:45:00,26.0,78.8,Partly cloudy,...,1.20,4.50,1,1,5:36 AM,6:32 PM,1:05 PM,1:14 AM,Waxing Gibbous,55
17,Belize,Belmopan,17.2500,-88.7700,America/Belize,1715849100,2024-05-16 02:45:00,26.0,78.9,Overcast,...,7.70,32.10,1,1,5:23 AM,6:20 PM,12:56 PM,1:04 AM,Waxing Gibbous,55
42,Cuba,Havana,23.1300,-82.3600,America/Havana,1715849100,2024-05-16 04:45:00,26.0,78.8,Clear,...,4.70,18.40,1,1,6:47 AM,8:04 PM,2:24 PM,2:44 AM,Waxing Gibbous,55
52,El Salvador,San Salvador,13.7100,-89.2000,America/El_Salvador,1715849100,2024-05-16 02:45:00,26.0,78.8,Moderate or heavy rain with thunder,...,20.40,28.10,2,2,5:30 AM,6:16 PM,1:00 PM,1:02 AM,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134404,Micronesia,Palikir,6.9167,158.1500,Pacific/Pohnpei,1775717100,2026-04-09 17:45:00,26.0,78.8,Overcast,...,3.15,4.75,1,1,6:22 AM,6:36 PM,No moonrise,11:31 AM,Waning Gibbous,66
134809,Nigeria,Abuja,9.1758,7.1808,Africa/Lagos,1775889000,2026-04-11 07:30:00,26.0,78.9,Sunny,...,72.05,147.05,4,10,6:23 AM,6:41 PM,1:44 AM,1:36 PM,Waning Crescent,43
134829,Saint Lucia,Castries,14.0000,-61.0000,America/St_Lucia,1775889000,2026-04-11 02:30:00,26.0,78.8,Partly cloudy,...,6.65,10.45,1,1,5:53 AM,6:17 PM,1:34 AM,1:11 PM,Waning Crescent,41
134830,Saint Vincent and the Grenadines,Kingstown,13.1333,-61.2167,America/St_Vincent,1775889000,2026-04-11 02:30:00,26.0,78.8,Partly cloudy,...,7.50,11.80,1,1,5:55 AM,6:17 PM,1:34 AM,1:13 PM,Waning Crescent,41
134882,Angola,Luanda,-8.8383,13.2344,Africa/Luanda,1775975400,2026-04-12 07:30:00,26.0,78.8,Partly Cloudy,...,11.55,13.15,1,1,6:10 AM,6:06 PM,1:38 AM,2:24 PM,Waning Crescent,33

# 2

In [40]:
df[df["moon_phase"]=="Waning Crescent"]

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
3115,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1717164900,2024-05-31 18:45:00,21.3,70.3,Sunny,...,3.50,7.30,1,1,4:42 AM,7:00 PM,12:42 AM,12:17 PM,Waning Crescent,47
3116,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1717164900,2024-05-31 16:15:00,25.0,77.0,Overcast,...,27.20,29.70,2,3,5:10 AM,8:07 PM,1:41 AM,1:10 PM,Waning Crescent,47
3117,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1717164900,2024-05-31 15:15:00,25.0,77.0,Partly cloudy,...,6.80,20.90,1,1,5:31 AM,8:01 PM,1:44 AM,1:23 PM,Waning Crescent,47
3118,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1717164900,2024-05-31 16:15:00,14.6,58.2,Sunny,...,0.60,0.90,1,1,6:19 AM,9:25 PM,2:56 AM,2:25 PM,Waning Crescent,47
3119,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1717164900,2024-05-31 15:15:00,29.0,84.2,Partly cloudy,...,8.30,32.20,1,1,6:15 AM,5:54 PM,12:29 AM,1:01 PM,Waning Crescent,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,16.35,18.15,2,2,6:18 AM,6:38 PM,2:36 AM,2:31 PM,Waning Crescent,31
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,61.15,64.45,3,8,5:41 AM,6:14 PM,2:02 AM,1:21 PM,Waning Crescent,35
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,7.45,15.35,1,1,5:51 AM,6:17 PM,2:06 AM,1:45 PM,Waning Crescent,34
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,5.45,6.15,1,1,6:14 AM,6:01 PM,1:26 AM,2:30 PM,Waning Crescent,33
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,19.85,20.55,2,2,6:04 AM,5:49 PM,1:10 AM,2:22 PM,Waning Crescent,33

# 3

In [41]:
df[df["moon_illumination"]==0]

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
4285,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1717682400,2024-06-06 18:30:00,18.0,64.3,Patchy rain nearby,...,3.90,8.20,1,1,4:40 AM,7:04 PM,4:02 AM,7:18 PM,New Moon,0
4286,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1717682400,2024-06-06 16:00:00,32.0,89.6,Sunny,...,4.50,5.10,1,1,5:08 AM,8:11 PM,4:31 AM,8:41 PM,New Moon,0
4287,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1717682400,2024-06-06 15:00:00,32.0,89.6,Sunny,...,16.40,34.80,2,2,5:29 AM,8:04 PM,4:58 AM,8:33 PM,New Moon,0
4288,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1717682400,2024-06-06 16:00:00,22.5,72.6,Patchy rain nearby,...,2.20,3.40,1,1,6:17 AM,9:29 PM,5:43 AM,10:03 PM,New Moon,0
4289,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1717682400,2024-06-06 15:00:00,26.0,78.8,Partly cloudy,...,7.30,25.20,1,1,6:17 AM,5:55 PM,6:04 AM,5:55 PM,New Moon,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130555,South Korea,Seoul,37.5664,126.9997,Asia/Seoul,1773989100,2026-03-20 15:45:00,13.3,55.9,Sunny,...,26.95,35.85,2,3,6:36 AM,6:43 PM,6:56 AM,8:14 PM,Waxing Crescent,0
130567,Timor-Leste,Dili,-8.5586,125.5736,Asia/Dili,1773989100,2026-03-20 15:45:00,26.4,79.5,Patchy rain nearby,...,2.65,2.85,1,1,6:42 AM,6:49 PM,7:28 AM,7:41 PM,Waxing Crescent,0
130569,Tonga,Nuku`Aloia,-21.1333,-175.2000,Pacific/Tongatapu,1773989100,2026-03-20 19:45:00,28.0,82.4,Light rain shower,...,3.15,4.55,1,1,6:44 AM,6:52 PM,7:28 AM,7:28 PM,Waxing Crescent,0
130574,Tuvalu,Funafuti,-8.5167,179.2167,Pacific/Funafuti,1773989100,2026-03-20 18:45:00,28.1,82.6,Partly cloudy,...,2.05,2.65,1,1,6:07 AM,6:14 PM,6:45 AM,6:59 PM,Waxing Crescent,0
130582,Vanuatu,Port Vila,-17.7333,168.3167,Pacific/Efate,1773989100,2026-03-20 17:45:00,29.0,84.2,Partly cloudy,...,2.35,3.05,1,1,5:51 AM,5:58 PM,6:35 AM,6:37 PM,Waxing Crescent,0

# 4

In [42]:
df[df["condition_text"]=="Light rain shower"]

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
135,Papua New Guinea,Port Moresby,-9.4600,147.1900,Pacific/Port_Moresby,1715849100,2024-05-16 18:45:00,26.2,79.1,Light rain shower,...,2.80,6.40,1,1,6:17 AM,5:58 PM,1:08 PM,12:24 AM,Waxing Gibbous,55
399,Austria,Vienna,48.2000,16.3700,Europe/Vienna,1715961600,2024-05-17 18:00:00,14.0,57.2,Light rain shower,...,1.60,2.50,1,1,5:12 AM,8:30 PM,2:07 PM,2:57 AM,Waxing Gibbous,64
413,Brazil,Bras,-2.0800,-58.1700,America/Manaus,1715961600,2024-05-17 12:00:00,29.6,85.2,Light rain shower,...,0.50,0.50,1,1,5:49 AM,5:50 PM,1:44 PM,1:21 AM,Waxing Gibbous,64
494,Maldives,Felidhoo,3.4800,73.5300,Indian/Maldives,1715961600,2024-05-17 21:00:00,29.5,85.2,Light rain shower,...,1.90,5.40,1,1,5:54 AM,6:11 PM,1:40 PM,1:23 AM,Waxing Gibbous,64
546,Slovakia,Bratislava,48.1500,17.1200,Europe/Bratislava,1715961600,2024-05-17 18:00:00,13.0,55.4,Light rain shower,...,3.90,4.20,1,1,5:10 AM,8:27 PM,2:04 PM,2:54 AM,Waxing Gibbous,64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134901,Brazil,Bras,-2.0833,-58.1667,America/Manaus,1775975400,2026-04-12 02:30:00,23.1,73.6,Light rain shower,...,9.15,11.05,1,1,5:52 AM,5:56 PM,1:43 AM,2:10 PM,Waning Crescent,31
134916,Comoros,Moroni,-11.7042,43.2403,Indian/Comoro,1775975400,2026-04-12 09:30:00,30.3,86.5,Light rain shower,...,4.05,5.45,1,1,6:12 AM,6:04 PM,1:30 AM,2:24 PM,Waning Crescent,34
134926,Dominica,Roseau,15.3000,-61.4000,America/Dominica,1775975400,2026-04-12 02:30:00,25.1,77.2,Light rain shower,...,11.05,17.25,1,1,5:53 AM,6:19 PM,2:20 AM,2:03 PM,Waning Crescent,31
134990,Iran,Chi Chi Khvar,36.2625,46.5900,Asia/Tehran,1775975400,2026-04-12 10:00:00,7.9,46.2,Light rain shower,...,18.45,91.65,2,2,5:55 AM,6:55 PM,3:05 AM,1:31 PM,Waning Crescent,34
135026,Samoa,Apia,-13.8333,-171.7333,Pacific/Apia,1775975400,2026-04-12 19:30:00,28.7,83.6,Light rain shower,...,3.25,4.75,1,1,6:33 AM,6:22 PM,1:25 AM,2:30 PM,Waning Crescent,38

# 5

In [54]:
df[(df["temperature_celsius"]==23.0) & (df["condition_text"]=="Sunny")]

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,10.40,18.40,1,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55
62,Gambia,Banjul,13.4500,-16.5800,Africa/Banjul,1715849100,2024-05-16 08:45:00,23.0,73.4,Sunny,...,12.90,59.60,1,2,6:40 AM,7:26 PM,2:01 PM,2:04 AM,Waxing Gibbous,55
235,Costa Rica,San Juan,9.9700,-84.0800,America/Costa_Rica,1715868000,2024-05-16 08:00:00,23.0,73.4,Sunny,...,20.80,23.50,2,2,5:15 AM,5:51 PM,12:42 PM,12:37 AM,Waxing Gibbous,55
289,Lebanon,Beirut,33.8700,35.5100,Asia/Beirut,1715868000,2024-05-16 17:00:00,23.0,73.4,Sunny,...,8.30,15.00,1,1,5:36 AM,7:34 PM,1:03 PM,1:57 AM,Waxing Gibbous,55
383,Uzbekistan,Tashkent,41.3200,69.2500,Asia/Tashkent,1715868000,2024-05-16 19:00:00,23.0,73.4,Sunny,...,2.30,2.80,1,1,5:03 AM,7:36 PM,12:32 PM,1:53 AM,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125535,Chad,N'djamena,12.1131,15.0492,Africa/Ndjamena,1771742700,2026-02-22 07:45:00,23.0,73.4,Sunny,...,62.05,265.35,3,8,6:18 AM,6:08 PM,9:42 AM,10:42 PM,Waxing Crescent,22
128202,Sudan,Khartoum,15.5881,32.5342,Africa/Khartoum,1772865000,2026-03-07 08:30:00,23.0,73.4,Sunny,...,19.75,80.05,2,2,6:03 AM,5:59 PM,9:26 PM,8:21 AM,Waning Gibbous,88
129015,Uganda,Kampala,0.3156,32.5656,Africa/Kampala,1773297900,2026-03-12 09:45:00,23.0,73.4,Sunny,...,42.75,42.85,3,5,6:56 AM,7:03 PM,1:20 AM,1:43 PM,Waning Crescent,46
132289,Qatar,Doha,25.2867,51.5333,Asia/Qatar,1774764900,2026-03-29 09:15:00,23.0,73.4,Sunny,...,40.35,142.45,2,4,5:29 AM,5:49 PM,2:32 PM,3:09 AM,Waxing Gibbous,82
132370,Burundi,Bujumbura,-3.3761,29.3600,Africa/Bujumbura,1774852200,2026-03-30 08:30:00,23.0,73.4,Sunny,...,14.45,14.65,1,2,6:05 AM,6:09 PM,4:20 PM,3:52 AM,Waxing Gibbous,89

## Data Cleaning

### cleaning numerical columns with charecters

In [59]:
df.head(10)

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,10.4,18.4,1,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55
5,Antigua and Barbuda,Saint John's,17.12,-61.85,America/Antigua,1715849100,2024-05-16 04:45:00,26.0,78.8,Partly cloudy,...,1.2,4.5,1,1,5:36 AM,6:32 PM,1:05 PM,1:14 AM,Waxing Gibbous,55
6,Argentina,Buenos Aires,-34.59,-58.67,America/Argentina/Buenos_Aires,1715849100,2024-05-16 05:45:00,8.0,46.4,Clear,...,4.0,5.3,1,1,7:43 AM,5:59 PM,2:36 PM,1:04 AM,Waxing Gibbous,55
7,Armenia,Yerevan,40.18,44.51,Asia/Yerevan,1715849100,2024-05-16 12:45:00,19.0,66.2,Partly cloudy,...,0.8,0.9,1,1,5:45 AM,8:12 PM,1:17 PM,2:31 AM,Waxing Gibbous,55
8,Australia,Canberra,-35.28,149.22,Australia/Sydney,1715849100,2024-05-16 18:45:00,9.0,48.2,Clear,...,3.7,5.4,1,1,6:52 AM,5:07 PM,1:31 PM,No moonset,Waxing Gibbous,55
9,Austria,Vienna,48.20,16.37,Europe/Vienna,1715849100,2024-05-16 10:45:00,16.0,60.8,Partly cloudy,...,3.7,4.4,1,1,5:14 AM,8:29 PM,1:00 PM,2:42 AM,Waxing Gibbous,55

In [61]:
df.drop(['sunrise','sunset','moonrise', 'moonset','moon_phase','moon_illumination'], axis=1, inplace=True)

In [62]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,gust_mph,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,9.5,15.3,277.00,103.0,1.10,0.20,8.40,26.60,1,1
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,11.4,18.4,193.60,97.3,0.90,0.10,1.10,2.00,1,1
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,13.9,22.3,540.70,12.2,65.10,13.40,10.40,18.40,1,1
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,8.5,13.7,170.20,64.4,1.60,0.20,0.70,0.90,1,1
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,12.5,20.2,2964.00,19.0,72.70,31.50,183.40,262.30,5,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,4.7,7.6,379.85,46.0,7.95,2.35,16.35,18.15,2,2
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,8.0,12.9,1034.85,62.0,30.75,17.85,61.15,64.45,3,8
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,4.6,7.5,147.85,47.0,3.35,1.35,7.45,15.35,1,1
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,11.3,18.2,118.85,54.0,2.35,1.85,5.45,6.15,1,1
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,5.7,9.1,200.85,35.0,7.75,2.05,19.85,20.55,2,2

In [63]:
df.rename(columns={
    'air_quality_Carbon_Monoxide': 'co',
    'air_quality_Ozone': 'ozone',
    'air_quality_PM2.5': 'pm25',
    'air_quality_PM10': 'pm10'
}, inplace=True)

In [64]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,gust_mph,gust_kph,co,ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,pm25,pm10,air_quality_us-epa-index,air_quality_gb-defra-index
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,9.5,15.3,277.00,103.0,1.10,0.20,8.40,26.60,1,1
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,11.4,18.4,193.60,97.3,0.90,0.10,1.10,2.00,1,1
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,13.9,22.3,540.70,12.2,65.10,13.40,10.40,18.40,1,1
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,8.5,13.7,170.20,64.4,1.60,0.20,0.70,0.90,1,1
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,12.5,20.2,2964.00,19.0,72.70,31.50,183.40,262.30,5,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,4.7,7.6,379.85,46.0,7.95,2.35,16.35,18.15,2,2
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,8.0,12.9,1034.85,62.0,30.75,17.85,61.15,64.45,3,8
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,4.6,7.5,147.85,47.0,3.35,1.35,7.45,15.35,1,1
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,11.3,18.2,118.85,54.0,2.35,1.85,5.45,6.15,1,1
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,5.7,9.1,200.85,35.0,7.75,2.05,19.85,20.55,2,2

In [58]:
df.duplicated().sum()

np.int64(0)

In [65]:
df['last_updated'] = pd.to_datetime(df['last_updated'])

In [68]:
df['year'] = df['last_updated'].dt.year
df['month'] = df['last_updated'].dt.month
df['hour'] = df['last_updated'].dt.hour
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,pm25,pm10,air_quality_us-epa-index,air_quality_gb-defra-index,year,month,hour
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,103.0,1.10,0.20,8.40,26.60,1,1,2024,5,13
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,97.3,0.90,0.10,1.10,2.00,1,1,2024,5,10
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,12.2,65.10,13.40,10.40,18.40,1,1,2024,5,9
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,64.4,1.60,0.20,0.70,0.90,1,1,2024,5,10
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,19.0,72.70,31.50,183.40,262.30,5,10,2024,5,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,46.0,7.95,2.35,16.35,18.15,2,2,2026,4,2
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,62.0,30.75,17.85,61.15,64.45,3,8,2026,4,13
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,47.0,3.35,1.35,7.45,15.35,1,1,2026,4,9
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,54.0,2.35,1.85,5.45,6.15,1,1,2026,4,8
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,35.0,7.75,2.05,19.85,20.55,2,2,2026,4,8

In [70]:
df = df[(df['temperature_celsius'] > -50) & (df['temperature_celsius'] < 60)]
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,pm25,pm10,air_quality_us-epa-index,air_quality_gb-defra-index,year,month,hour
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,103.0,1.10,0.20,8.40,26.60,1,1,2024,5,13
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,97.3,0.90,0.10,1.10,2.00,1,1,2024,5,10
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,12.2,65.10,13.40,10.40,18.40,1,1,2024,5,9
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,64.4,1.60,0.20,0.70,0.90,1,1,2024,5,10
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,19.0,72.70,31.50,183.40,262.30,5,10,2024,5,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,46.0,7.95,2.35,16.35,18.15,2,2,2026,4,2
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,62.0,30.75,17.85,61.15,64.45,3,8,2026,4,13
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,47.0,3.35,1.35,7.45,15.35,1,1,2026,4,9
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,54.0,2.35,1.85,5.45,6.15,1,1,2026,4,8
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,35.0,7.75,2.05,19.85,20.55,2,2,2026,4,8

In [72]:
df['humidity'] = df['humidity'].astype(int)

In [75]:
df.drop_duplicates(inplace=True)

In [71]:
df = df[(df['humidity'] >= 0) & (df['humidity'] <= 100)]

In [14]:
df.columns = df.columns.str.strip()

In [15]:
df['last_updated'] = pd.to_datetime(df['last_updated'])

In [16]:
df

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,79.8,Partly Cloudy,...,8.40,26.60,1,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,66.2,Partly cloudy,...,1.10,2.00,1,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,73.4,Sunny,...,10.40,18.40,1,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,43.3,Light drizzle,...,0.70,0.90,1,1,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,78.8,Partly cloudy,...,183.40,262.30,5,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30:00,19.1,66.3,Partly Cloudy,...,16.35,18.15,2,2,6:18 AM,6:38 PM,2:36 AM,2:31 PM,Waning Crescent,31
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30:00,34.2,93.6,Sunny,...,61.15,64.45,3,8,5:41 AM,6:14 PM,2:02 AM,1:21 PM,Waning Crescent,35
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30:00,19.3,66.7,Sunny,...,7.45,15.35,1,1,5:51 AM,6:17 PM,2:06 AM,1:45 PM,Waning Crescent,34
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30:00,18.5,65.3,Sunny,...,5.45,6.15,1,1,6:14 AM,6:01 PM,1:26 AM,2:30 PM,Waning Crescent,33
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30:00,17.4,63.3,Sunny,...,19.85,20.55,2,2,6:04 AM,5:49 PM,1:10 AM,2:22 PM,Waning Crescent,33

In [79]:
df['temp_category'] = pd.cut(df['temperature_celsius'],
                            bins=[-50, 15, 30, 60],
                            labels=['cold', 'moderate', 'hot'])